### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by ErnestDaDev** [autoussd/autoussd-sample-flutter#1]
I am getting this error, I followed the instructions to add to an existing project, Is there something I am missing?

D/AutoUssdFlutterPlugin( 3950): On Method Call
E/MethodChannel#autoussdflutter( 3950): Failed to handle method call
E/MethodChannel#autoussdflutter( 3950): java.lang.IllegalStateException: Instance not initialized. Call AutoUssd.init(activity) first
E/MethodChannel#autoussdflutter( 3950): 	at com.autoussd.AutoUssd$Companion.getInstance(Unknown Source:3)
E/MethodChannel#autoussdflutter( 3950): 	at com.autoussd.autoussdflutter.AutoUssdFlutterPlugin.onMethodCall(AutoUssdFlutterPlugin.kt:172)
E/MethodChannel#autoussdflutter( 3950): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#autoussdflutter( 3950): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#autoussdflutter( 3950): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#autoussdflutter( 3950): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#autoussdflutter( 3950): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#autoussdflutter( 3950): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#autoussdflutter( 3950): 	at android.os.Looper.loop(Looper.java:238)
E/MethodChannel#autoussdflutter( 3950): 	at android.app.ActivityThread.main(ActivityThread.java:7890)
E/MethodChannel#autoussdflutter( 3950): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#autoussdflutter( 3950): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#autoussdflutter( 3950): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:983)

**Comment by Meghatronics** [comment]
Is a fix for this issue available now? I'm experiencing the same exact same error.
